# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pressed', models.CharField(max_length=250)),
                ('duration_Seconds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RugAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('alert_duration_Seconds', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('auto_stop_minutes', models.IntegerField(default=0)),
                ('stop_minutes', models.IntegerField(default=0)),
                ('is_playback_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='WebRadio',
            new_name='MP3Playback',
        ),
        migrations.RenameField(
            model_name='alarmclock',
            old_name='webradio',
            new_name='mp3playback',
        ),
        migrations.RenameField(
            model_name='mp3playback',
            old_name='url',
            new_name='mp3_path',
        ),
        migrations.AddField(
            model_name='alarmclock',
            name='stop_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rugalert',
            name='alarm_clock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.AlarmClock'),
        ),
        migrations.AddField(
            model_name='rugalert',
            name='mp3_playback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.MP3Playback'),
        ),
        migrations.AddField(
            model_name='alertnotified',
            name='alert_rug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.RugAlert'),
        ),
    ]
