# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_auto_20180107_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarmclock',
            old_name='mp3playback',
            new_name='mp3_playback',
        ),
    ]
