# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0005_auto_20180108_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertnotified',
            name='alert_rug',
        ),
        migrations.RemoveField(
            model_name='alertrug',
            name='alarm_clock',
        ),
        migrations.RemoveField(
            model_name='alertrug',
            name='alert_duration_Seconds',
        ),
        migrations.RemoveField(
            model_name='alertrug',
            name='auto_stop_seconds',
        ),
        migrations.RemoveField(
            model_name='alertrug',
            name='name',
        ),
    ]
