# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0006_auto_20180117_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertnotified',
            name='duration_Seconds',
            field=models.FloatField(),
        ),
    ]
