# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0008_auto_20180121_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertrug',
            old_name='active_audio',
            new_name='is_audio_active',
        ),
        migrations.RenameField(
            model_name='alertrug',
            old_name='active_camera',
            new_name='is_camera_active',
        ),
        migrations.RenameField(
            model_name='alertrug',
            old_name='active_light',
            new_name='is_light_active',
        ),
        migrations.RenameField(
            model_name='alertrug',
            old_name='alert_message',
            new_name='is_message_active',
        ),
    ]
